### ISSUE TITLE
口コミボタンはあるが口コミモーダルではないページのURLで調査すると`Application error`になる

### ISSUE THREAD

**Issue by pekorinko** [pekorinko/review_check#105]
### 以下のようなページのURLで調査すると`Application error`になる
![image](https://user-images.githubusercontent.com/61894818/122622372-72f0e980-d0d3-11eb-9854-7691555d450a.png)
### エラー
- `2021-06-18T22:52:17.856158+00:00 heroku[web.1]: Error R14 (Memory quota exceeded)`
- `2021-06-18T22:52:26.843599+00:00 app[web.1]: E, [2021-06-19T07:52:26.838509 #11] ERROR -- : [38c336f3-8134-4021-82fd-120551c88cca] #<Selenium::WebDriver::Error::UnknownError: unknown error: session deleted because of page crash`
- `2021-06-18T22:52:26.843607+00:00 app[web.1]: from unknown error: cannot determine loading status`
- `2021-06-18T22:52:26.843609+00:00 app[web.1]: from tab crashed`
`2021-06-18T22:52:26.843612+00:00 app[web.1]: E, [2021-06-19T07:52:26.843449 #11] ERROR -- : [38c336f3-8134-4021-82fd-120551c88cca] #0 0x55dc6f64b949 <unknown>`
- `2021-06-18T22:52:42.053812+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/results" host=review-check.herokuapp.com request_id=15be7e4b-4521-48ef-ab85-41196e07bd39 fwd="125.30.20.12" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https`
- `2021-06-18T22:52:47.310240+00:00 app[web.1]: E, [2021-06-19T07:52:47.308721 #11] ERROR -- : [15be7e4b-4521-48ef-ab85-41196e07bd39] #<Selenium::WebDriver::Error::JavascriptError: javascript error: Cannot read property 'getElementsByTagName' of undefined`
- `2021-06-18T22:52:47.310241+00:00 app[web.1]: E, [2021-06-19T07:52:47.309052 #11] ERROR -- : [15be7e4b-4521-48ef-ab85-41196e07bd39] #0 0x562d35c7d949 <unknown>`
### `Selenium::WebDriver::Error::UnknownError: unknown error: session deleted because of page crash`について
- メモリ不足が原因のようなので`chrome_options`を追加した↓
- https://stackoverflow.com/questions/53902507/unknown-error-session-deleted-because-of-page-crash-from-unknown-error-cannot
### 上記記事を参考に`chrome_options`に`--no-sandbox`と`--disable-dev-shm-usage`を追加
```
【lib/my_tools/selenium_tool.rb】
module MyTools
  class SeleniumTool
    attr_reader :url
    def initialize(url)
      @url = url
      options = Selenium::WebDriver::Chrome::Options.new
      options.add_argument('--headless')
      caps =
        if Rails.env.production?
          Selenium::WebDriver::Remote::Capabilities.chrome(
            'chromeOptions' => {
              binary: ENV['GOOGLE_CHROME_SHIM'],
              args: %w[
                --headless
                --disable-gpu
                window-size=1280x800
                --no-sandbox　←追加
                --disable-dev-shm-usage　←追加
              ],
            },
          )
        end
      if Rails.env.production?
        @driver =
          Selenium::WebDriver.for :chrome,
                                  options: options,
                                  desired_capabilities: caps
      else
        @driver = Selenium::WebDriver.for :chrome, options: options
      end
```
## 結果
- `Application error`は出なくなったが「口コミの取得に失敗しました」アラートが出る
### エラー
- `2021-06-19T00:29:17.366018+00:00 app[web.1]: E, [2021-06-19T09:29:17.364125 #11] ERROR -- : [3de7500b-a683-4d69-b1f2-ae08afc70713] #<Selenium::WebDriver::Error::InvalidSessionIdError: invalid session id>`
- `2021-06-19T00:29:17.366026+00:00 app[web.1]: E, [2021-06-19T09:29:17.365021 #11] ERROR -- : [3de7500b-a683-4d69-b1f2-ae08afc70713] #0 0x561e95fdd949 <unknown>`
### 考えられる原因
- 口コミボタンがある検索画面やGoogleMapのURLを入力すると２回ヘッドレスモードでブラウザを起動する
- そのためメモリが枯渇してしまい`Selenium::WebDriver::Error::InvalidSessionIdError:
           invalid session id`が出ている
### 解決策（仮）
- ` /dev/shm`が使えるdocker containerのデフォルトの容量が64MBしかないため` /dev/shm`の容量を上げる
- 参考記事：https://medium.com/the-curve-tech-blog/dealing-with-cryptic-selenium-webdriver-error-invalidsessioniderror-errors-9c15abc68fdf

**Comment by pekorinko** [comment]
- df：ディスク容量を確認するコマンド
  - https://www.ibm.com/docs/ja/aix/7.1?topic=system-displaying-available-space-file-df-command 
- 本来であれば/dev/shmにtmpfsがマウントされているはずだが `df -h`を実行しても/dev/shmもtmpfsも見当たらない
  - https://blog.katsubemakito.net/linux/ramdisk-tmpfs 
```
midorikamimura@uemuramidorinoMacBook review_check % df -h
Filesystem       Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1s5s1  466Gi   14Gi  398Gi     4%  553757 4881899123    0%   /
devfs           195Ki  195Ki    0Bi   100%     675          0  100%   /dev
/dev/disk1s4    466Gi  4.0Gi  398Gi     1%       5 4882452875    0%   /System/Volumes/VM
/dev/disk1s2    466Gi  452Mi  398Gi     1%    1713 4882451167    0%   /System/Volumes/Preboot
/dev/disk1s6    466Gi  2.5Mi  398Gi     1%      18 4882452862    0%   /System/Volumes/Update
/dev/disk1s1    466Gi   48Gi  398Gi    11% 1186516 4881266364    0%   /System/Volumes/Data
map auto_home     0Bi    0Bi    0Bi   100%       0          0  100%   /System/Volumes/Data/home
```

**Comment by pekorinko** [comment]
## WebDriverを作った後、`quit`で後始末する
### 結果
- `2021-06-24T14:01:10.718692+00:00 app[web.1]: E, [2021-06-24T23:01:10.718447 #11] ERROR -- : [7f8072fa-b1fb-45c8-99d8-ffaf71946e9b] #<Errno::ECONNREFUSED: Failed to open TCP connection to 127.0.0.1:9516 (Connection refused - connect(2) for "127.0.0.1" port 9516)>`
- `2021-06-24T14:01:10.718749+00:00 app[web.1]: E, [2021-06-24T23:01:10.718592 #11] ERROR -- : [7f8072fa-b1fb-45c8-99d8-ffaf71946e9b] /app/vendor/ruby-2.7.2/lib/ruby/2.7.0/net/http.rb:960:in `initialize'`

**Comment by pekorinko** [comment]
## 口コミボタンはあるが口コミモーダルではないURLだとHerokuから日本語のGoogleを使うためのパラメータ付与ができない
```
【エラー】
TypeError (no implicit conversion of nil into String):
  
app/controllers/results_controller.rb:70:in `+'
app/controllers/results_controller.rb:70:in `localized_url'
app/controllers/results_controller.rb:35:in `create'
```
```
【results_controller.rb】
def localized_url(url)
    a, b = url.split('#')
    localized_query = '&gl=jp&hl=ja&gws_rd=cr&pws=0'
    a + localized_query + '#' + b
  end
```
### 口コミURL
https://www.google.com/search?q=%E6%B1%9F%E6%88%B8%E6%9D%B1%E4%BA%AC%E3%81%9F%E3%81%A6%E3%82%82%E3%81%AE%E5%9C%92&rlz=1C5CHFA_enJP939JP939&oq=%E6%B1%9F%E6%88%B8%E6%9D%B1%E4%BA%AC&aqs=chrome.2.69i57j0i433j0i131i433j0l7.6765j0j9&sourceid=chrome&ie=UTF-8#lrd=0x60188d9b1a7a9187:0x247f2b088a47a767,1,,,
### 口コミボタンはあるが口コミモーダルではないURL
- Google検索結果
https://www.google.com/search?q=%E6%B1%9F%E6%88%B8%E6%9D%B1%E4%BA%AC%E3%81%9F%E3%81%A6%E3%82%82%E3%81%AE%E5%9C%92&rlz=1C5CHFA_enJP939JP939&oq=%E6%B1%9F%E6%88%B8%E6%9D%B1%E4%BA%AC&aqs=chrome.2.69i57j0i433j0i131i433j0l7.6765j0j9&sourceid=chrome&ie=UTF-8
## 口コミモーダルではないURLでもパラメータ付与できる仕様に変更
```
【results_controller.rb】
def localized_url(url)
    if url.include?('#')
      a, b = url.split('#')
      localized_query = '&gl=jp&hl=ja&gws_rd=cr&pws=0'
      return a + @localized_query + '#' + b
    else
      localized_query = '&gl=jp&hl=ja&gws_rd=cr&pws=0'
      return url.to_s + localized_query
    end
  end
``` 
- **ローカルではGoogleの検索結果でもスクレイピングできるようになった**
- **Herokuでは以下エラーが出てしまう**
`Completed 500 Internal Server Error in 2ms (Allocations: 351)`
`[002731e1-336e-4c40-b01f-d5d1ef33ec0e] TypeError (no implicit conversion of nil into String):`

**Comment by pekorinko** [comment]
## 検索結果URLでもスクレイピングできるURLとできないURLがある
- できるURL
https://www.google.com/search?q=%E3%82%B8%E3%83%96%E3%83%AA%E7%BE%8E%E8%A1%93%E9%A4%A8&rlz=1C5CHFA_enJP939JP939&oq=%E3%82%B8%E3%83%96%E3%83%AA%E7%BE%8E%E8%A1%93%E9%A4%A8&aqs=chrome..69i57j0l9.6497j0j9&sourceid=chrome&ie=UTF-8
- できないURL
https://www.google.com/search?q=%E3%83%AF%E3%83%B3%E3%82%BF%E3%83%B3%E9%BA%BA+%E6%BA%80%E6%9C%88&rlz=1C5CHFA_enJP939JP939&oq=%E3%83%AF%E3%83%B3%E3%82%BF%E3%83%B3%E9%BA%BA%E3%80%80%E6%BA%80%E6%9C%88&aqs=chrome.0.69i59j0i10l4.7125j0j9&sourceid=chrome&ie=UTF-8
  - 表示されるエラー
  `E, [2021-06-28T20:47:03.257720 #11] ERROR -- : [dce71173-bd22-44f0-928e-5ff42b364cf6] #<Selenium::WebDriver::Error::JavascriptError: javascript error: Cannot read property 'getElementsByTagName' of undefined`

**Comment by pekorinko** [comment]
## 東京ディズニーランドのURLがスクレイピングできない
`2021-06-28T22:43:27.775742+00:00 app[web.1]: E, [2021-06-29T07:43:27.775422 #11] ERROR -- : [f87547c0-9e1f-473d-ad68-388b5e1770b4] #<Selenium::WebDriver::Error::InvalidSessionIdError: invalid session id>`
`2021-06-28T22:43:27.775778+00:00 app[web.1]: E, [2021-06-29T07:43:27.775569 #11] ERROR -- : [f87547c0-9e1f-473d-ad68-388b5e1770b4] #0 0x55bfa9370949 <unknown>`

https://www.google.com/search?q=%E6%9D%B1%E4%BA%AC%E3%83%87%E3%82%A3%E3%82%BA%E3%83%8B%E3%83%BC%E3%83%A9%E3%83%B3%E3%83%89&rlz=1C5CHFA_enJP939JP939&oq=%E6%9D%B1%E4%BA%AC%E3%83%87%E3%82%A3%E3%82%BA%E3%83%8B%E3%83%BC%E3%83%A9%E3%83%B3%E3%83%89&aqs=chrome.0.69i59j0j0i433j0i131i433j0l6.3717j0j9&sourceid=chrome&ie=UTF-8#lrd=0x60187d03114737b3:0xe4d93636d509d3cb,1,,,
## 解決：以下のオプションを追加したらエラーが出ずにスクレイピングできるようになった
`--enable-features=NetworkService,NetworkServiceInProcess`
- 参考記事：https://stackoverflow.com/questions/56002701/selenium-webdriver-error-invalid-session-id

**Comment by pekorinko** [comment]
## 解決
### やったこと
- results_controller.rbの`@localized_query`を`localized_query`に変更
- Seleniumの待ち時間を13秒から10秒に変更（HerokuのエラーH12解消目的）
