### ISSUE TITLE
【リファクタリング】トップの検索履歴をcreated_at順に並び替えできない問題→【保留】原因分からないので全部やることやってから再考

### ISSUE THREAD

**Issue by pekorinko** [pekorinko/review_check#48]
## #26 の最後で起こった問題（以下、具体的内容）
- 現時点では既存の施設を検索した場合、palce_idが既に存在しているため、履歴の一番上には当該施設のHistoryは表示されない
- `Result.select('DISTINCT ON (place_id) *').order(place_id: :desc).limit(5)`の`order(place_id: :desc)`に関しては`('DISTINCT ON (place_id) *')`のカラムと合わせる必要があるため、このコードで`created_at`順に並べることはできない

```result_histories =
      Result.select('DISTINCT ON (place_id) *').order(place_id: :desc).limit(5)
```
をしたあとに改めて
  `result_histories = result_histories.order(:created_at)`としたがやはりplace_id:が降順に表示される

参考になりそうなURL：
https://qiita.com/cobot00/items/c02f3307bb482580e94d

**Comment by pekorinko** [comment]
## 解決に繋がりそうな記事
- https://qiita.com/pione30/items/4ae61ed58b57effd6874
- DISTINCT ON を使った例でデータの集合自体は正しく取得できるので, そのクエリをサブクエリとしてさらに created_at でソートしてあげれば上手くいくとのこと
```
Result
      .select(:place_id)
      .where(id: Result.select('DISTINCT ON (place_id) *'))
      .order(:place_id, created_at: :desc)
      .order(created_at: :desc)
```
- 以下エラーになる
```
ActiveRecord::StatementInvalid (PG::SyntaxError: ERROR:  subquery has too many columns
LINE 1: ...s"."place_id" FROM "results" WHERE "results"."id" IN (SELECT...
                                                             ^
):
```
![image](https://user-images.githubusercontent.com/61894818/116927452-a5b35f80-ac96-11eb-955c-93473e0327e7.png)

**Comment by pekorinko** [comment]
## 参考記事をヒントに試したこと１
- やったこと：`place_id`でソートした後に`created_at`でソートする
- エラーにはならないが`created_at`で並び替えられていない
- 参考記事　https://qiita.com/cobot00/items/c02f3307bb482580e94d
```
Result
        .select('DISTINCT ON (place_id) *')
        .order(place_id: :desc)
        .order(created_at: :desc)
        .limit(5)
```

**Comment by pekorinko** [comment]
## 参考記事をヒントに試したこと２
- やったこと：`select('DISTINCT ON (place_id) *')`を`select('DISTINCT ON (place_id) id')`にしてみる
```
Result
      .select(:place_id)
      .where(id: Result.select('DISTINCT ON (place_id) id'))
      .order(:place_id, created_at: :desc)
      .order(created_at: :desc)
```
- 以下エラーが出る
```
ActiveModel::MissingAttributeError (missing attribute: star_ave):
  
app/controllers/results_controller.rb:44:in `block in new'
app/controllers/results_controller.rb:37:in `map'
app/controllers/results_controller.rb:37:in `new'
```
![image](https://user-images.githubusercontent.com/61894818/116928934-abaa4000-ac98-11eb-9b10-0cad408a0914.png)

**Comment by pekorinko** [comment]
## 参考記事をヒントに試したこと３
- やったこと：`order(place_id: :desc)`を`order(:place_id)`にしてみる
- 結果：`place_id`が昇順で表示される
```
Result
        .select('DISTINCT ON (place_id) *')
        .order(:place_id)
        .order(created_at: :desc)
        .limit(5
```
![image](https://user-images.githubusercontent.com/61894818/116929711-c6c97f80-ac99-11eb-9482-c038ff2ce249.png)

**Comment by pekorinko** [comment]
## 参考記事をヒントに試したこと4
- やったこと： 「解決に繋がりそうな記事」で試したコードに`limit(5)`を付ける
```
Result
        .select(:place_id)
        .where(id: Result.select('DISTINCT ON (place_id) *'))
        .order(:place_id, created_at: :desc)
        .order(created_at: :desc)
        .limit(5)
```
- 結果：「解決に繋がりそうな記事」と同様のエラーが出る
```
ActiveRecord::StatementInvalid (PG::SyntaxError: ERROR:  subquery has too many columns
LINE 1: ...s"."place_id" FROM "results" WHERE "results"."id" IN (SELECT...
                                                             ^
):
```
![image](https://user-images.githubusercontent.com/61894818/116927452-a5b35f80-ac96-11eb-955c-93473e0327e7.png)

**Comment by pekorinko** [comment]
## 「参考記事をヒントに試したこと4」のコードでどのようなSQLが発行されているのか
```
Processing by ResultsController#new as HTML
  Result Load (1.8ms)  
    SELECT "results"."place_id" FROM "results" 
    WHERE "results"."id" IN (SELECT DISTINCT ON (place_id) * FROM "results") 
    ORDER BY "results"."place_id" ASC, "results"."created_at" DESC 
    LIMIT $1  [["LIMIT", 5]]
```
- 上記SQLを発行した結果、コードの以下部分でエラーが出る
```
result_histories.map do |result_history|
```

## エラーの原因
- inの条件とサブクエリーの項目数が合っていないからエラーになっていると考えられる
```
【inの条件】
IN (SELECT DISTINCT ON (place_id) * FROM "results") 
```
```
【サブクエリ】
ORDER BY "results"."place_id" ASC, "results"."created_at" DESC LIMIT $1  [["LIMIT", 5]]
```

**Comment by pekorinko** [comment]
```
Result.select('DISTINCT ON (place_id) *').order(place_id: :desc).order(created_at: :desc).limit(5).to_sql
=> "SELECT DISTINCT ON (place_id) * FROM \"results\" ORDER BY \"results\".\"place_id\" DESC, \"results\".\"created_at\" DESC LIMIT 5"
```

**Comment by pekorinko** [comment]
## orderをかけた時にデフォルトスコープが設定されていないか確認する場合が多い
モデル：スコープ
→一覧表示する際にどの画面でも終了したイベントは普通表示しない
→それをいちいち夫々のコントローラーに書くのは面倒なのでモデルにメソッドとして書いておく
→これをデフォルトスコープとして設定すると常に適用される
→result.rbにデフォルトスコープは設定していないため、今回はこれが原因では無さそう

**Comment by pekorinko** [comment]
## `selenium_tool.rb`に以下の処理を書き加える
以下のコードが１を返すのか０を返すのかによって検索結果か口コミページかを判別出来る
![image](https://user-images.githubusercontent.com/61894818/117559133-bb24f100-b0bd-11eb-841a-509701351665.png)
## 0を返したときは口コミボタンを押す
単なる検索画面が来たときは'hqzQac'クラスを探してその中のaタグを開いてクリックすれば口コミURL取れる
`document.getElementsByClassName('hqzQac')[0].getElementsByTagName('a')[0].click()`
