### ISSUE TITLE
Heroku（testブランチをデプロイするまでの手順）

### ISSUE THREAD

**Issue by pekorinko** [pekorinko/review_check#85]
## 前提
- `improved_html_structure`ブランチから生やした`test`ブランチでHerokuへのデプロイを試みている
### 目的
- デプロイに慣れるため
- mainすべてマージされていなくてもHerokuに作業ブランチをデプロイすることで就活が始められると考えたため
- Herokuの環境下でこのサービスが正常に挙動するのか確かめるため
## 完了していること
- Herokuをmacにインストール
- `heroku login`は出来ている
### `improved_html_structure`ブランチと比較して`test`ブランチで変更したこと
- config/environments/production.rbの設定
  - https://qiita.com/kazukimatsumoto/items/a0daa7281a3948701c39

> 【引用箇所】
> Railsは本番環境での動的な画像の表示(というかプリコンパイル)がデフォルトでオフになっています。
> 画像を表示するために以下の記述をfalseからtrueに変更してください。（自分は31行目にありました）
> この記述により、assets以下のフォルダから動的にコンパイルしながらページを読み込みます。

```
【config/environments/production.rb】
#デフォルトでfalseとなっている以下の箇所をtrueに変更
  config.assets.compile = true
```
- 以下「躓いていること」でも記載したとおり、Herokuにデプロイする際に`Failed to install gems via Bundler.`が起こり、その原因としてHerokuとログインのbundlerとの間にバージョンの違いがあることが原因であると考えた
  - 上記問題を解消するために`rm gemfile.lock`して`Gemfile.lock`を一旦消してHerokuのbundlerバージョン2.2.16に合わせるために`bundle _2.2.16_ install`をした結果、現時点で`bundler (default: 2.2.19, default: 2.2.16)`となり、Gemfile.lockも`BUNDLED WITH 2.2.19`となった
  - もともと手を加える前は`Bundler version 2.1.4`であり、Gemfile.lockも`BUNDLED WITH 2.1.4`となっていた
## 躓いていること
- `git push heroku test:main`を試みたところ`Failed to install gems via Bundler.`のエラーが出た
  - エラーの詳細：https://github.com/pekorinko/review_check/issues/17#issuecomment-853865226
- 上記エラーの原因としてHerokuとローカルのbundlerのバージョンが異なることが原因と考えた
  - 参考記事：https://yumishin.com/heroku-push-error/#HerokuPushFailed_to_install_gems_via_Bundler 
- 試行錯誤した結果、現在、ローカルにもHerokuと同じバージョンの`2.2.16`がデフォルトとして入っているが並行して`2.2.19`もデフォルトとして入っている状況で`2.2.19`の方がローカルでは採用されているっぽい
###  試行錯誤の過程
- https://github.com/pekorinko/review_check/issues/17#issuecomment-854239817
- #84 ↑の続き
- 関連プルリク #83
### 現時点でのローカルのbundler内容
```
【Gemfile.lock】
BUNDLED WITH
   2.2.19
【ターミナル】
midorikamimura@uemuramidorinoMacBook review_check % gem list bundle

*** LOCAL GEMS ***

bundler (default: 2.2.19, default: 2.2.16)

midorikamimura@uemuramidorinoMacBook review_check % bundle -v
Bundler version 2.2.19
```
## ご相談したいこと
- `Failed to install gems via Bundler.`の原因がそもそも何か
  - 本当にHerokuとローカルのbundlerのバージョンが合致していないのが原因なのか？
  - Herokuにデプロイする上でローカルで使うBundlerのバージョンは基本的に何でもよいという記事があったため上記疑問を抱いた https://techracho.bpsinc.jp/hachi8833/2020_04_09/90793 
- もし`Failed to install gems via Bundler.`の原因がHerokuとローカルのbundlerのバージョンが合っていないことであるならば、どうすれば`2.2.16`のみをローカルのbundlerのデフォルトバージョンとして設定出来るか
- 現時点ではtestブランチのデプロイを試みているがmainに現在のプルリク内容がすべてマージされたらmainをHerokuに上げたいと考えている
  - その場合、Herokuへの再デプロイが必要になると思うがどのような手順で進めていくのか

**Comment by pekorinko** [comment]
## testブランチで`rails s`しようとしたら以下のようなエラーが出た
```
midorikamimura@uemuramidorinoMacBook review_check % rails s
bin/rails:3: warning: already initialized constant APP_PATH
/Users/midorikamimura/environment/review_check/bin/rails:3: warning: previous definition of APP_PATH was here
Traceback (most recent call last):
        14: from bin/rails:4:in `<main>'
        13: from bin/rails:4:in `require_relative'
        12: from /Users/midorikamimura/environment/review_check/config/boot.rb:3:in `<top (required)>'
        11: from /Users/midorikamimura/environment/review_check/config/boot.rb:3:in `require'
        10: from /Users/midorikamimura/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/setup.rb:10:in `<top (required)>'
         9: from /Users/midorikamimura/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/ui/shell.rb:88:in `silence'
         8: from /Users/midorikamimura/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/ui/shell.rb:136:in `with_level'
         7: from /Users/midorikamimura/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/setup.rb:10:in `block in <top (required)>'
         6: from /Users/midorikamimura/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler.rb:149:in `setup'
         5: from /Users/midorikamimura/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:26:in `setup'
         4: from /Users/midorikamimura/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:26:in `map'
         3: from /Users/midorikamimura/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/spec_set.rb:163:in `each'
         2: from /Users/midorikamimura/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/spec_set.rb:163:in `each'
         1: from /Users/midorikamimura/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:31:in `block in setup'
/Users/midorikamimura/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:302:in `check_for_activated_spec!': You have already activated bundler 2.2.16, but your Gemfile requires bundler 2.2.19. Since bundler is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports bundler as a default gem. (Gem::LoadError)
```
## 回答
bundle updateが全てに走ってしまったせいでrails sできなくなっていたと考えられる

**Comment by pekorinko** [comment]
## 回答
- Herokuで動かくbundlerのバージョンは基本何でも良い
- mimemagic (0.3.5) を現在のアプリでは使っているが（Herokuではmimemagic (0.3.5) ）使えない状況だからエラーが起こっている
```
Your bundle is locked to mimemagic (0.3.5) from rubygems repository
remote:        https://rubygems.org/ or installed locally, but that version can no longer be
remote:        found in that source. That means the author of mimemagic (0.3.5) has removed it.
remote:        You'll need to update your bundle to a version other than mimemagic (0.3.5) that
remote:        hasn't been removed in order to install.
remote:        Bundler Output: Fetching gem metadata from https://rubygems.org/............
remote:        Your bundle is locked to mimemagic (0.3.5) from rubygems repository
remote:        https://rubygems.org/ or installed locally, but that version can no longer be
remote:        found in that source. That means the author of mimemagic (0.3.5) has removed it.
remote:        You'll need to update your bundle to a version other than mimemagic (0.3.5) that
remote:        hasn't been removed in order to install.
```
- mimemagic
  - rails自体がこのgemに依存している
  - 依存している例：`selenium`をサービスで使ってはいる、seleniumのメソッドの中身は自分が使った訳ではない
  - 本サービスで`mimemagic (0.3.5)`を使わないようにする
    - Railsがmimemagic無くてbundle installできない
 https://qiita.com/suzuki_sh/items/84806ce231ed9b0f2e6d
```
【Gemfile】
gem 'rails', '~> 6.1.3.2'
【ターミナル上で】
bundle update rails
```

**Comment by pekorinko** [comment]
["x86_64-darwin-20"]→macでしか動かないgemを入れるな
38192b062eb44e42e817882a1104179f48cf2eec で
```
PLATFORMS
-  ruby
+  x86_64-darwin-20
```

**Comment by pekorinko** [comment]
HEADが今の最新のコミット
^を付けると一つ前

**Comment by pekorinko** [comment]
`git push -f test `

**Comment by pekorinko** [comment]
## GitHub上のtestブランチにも今回の変更は反映させる
- -f をつける 今回のように`git push -f origin test`する 
- リモートにpush したものをローカルで書き換えてpushしようとするときは`-f`が必要

**Comment by pekorinko** [comment]
## Precompiling assets failed.
`NoMethodError: undefined method `[]' for nil:NilClass`

heroku config:set RAILS_MASTER_KEY=`cat config/master.key`
https://qiita.com/koki_73/items/df7b4b001943e3ed69e7
↑環境変数を

**Comment by pekorinko** [comment]
herokuにpush出来なかった原因
- mimemagic https://qiita.com/suzuki_sh/items/84806ce231ed9b0f2e6d
- ["x86_64-darwin-20"]→macでしか動かないような設定がGemfile.lockに書かれてしまっている状態だったので`git reset HEAD^`をしてmacでしか動かないgemが入る前の段階に戻してあげた
- 過去にリモートにpushしたcomiitを書き換えてしまったのでHerokuにpushするさいに`-f`をつけた
- `Precompiling assets failed.`エラーがデプロイ時に出てしまってこれを解消するためにcredentialsファイルからシークレットキーなどを読み込むような設定にしている場合、サーバー側（今回はheroku）にmaster.keyの情報を渡しておく必要があるため以下のコマンド実行
```
$ heroku config:set RAILS_MASTER_KEY=`cat config/master.key`
```
Heroku上でSelenium動かないため、以下コマンド実行する必要あり
```
$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-google-chrome
```

**Comment by pekorinko** [comment]
デプロイは成功したがエラー画面が出たら`heroku --tails`でログの詳細を見る


## ブランチ片付け作業を行って、mainブランチをherokuにデプロイするのが良い
mainブランチにデプロイする際は以下の作業を再度行う
```
herokuにpush出来なかった原因
- mimemagic https://qiita.com/suzuki_sh/items/84806ce231ed9b0f2e6d
- ["x86_64-darwin-20"]→macでしか動かないような設定がGemfile.lockに書かれてしまっている状態だったので`git reset HEAD^`をしてmacでしか動かないgemが入る前の段階に戻してあげた
- 過去にリモートにpushしたcomiitを書き換えてしまったのでHerokuにpushするさいに`-f`をつけた
- `Precompiling assets failed.`エラーがデプロイ時に出てしまってこれを解消するためにcredentialsファイルからシークレットキーなどを読み込むような設定にしている場合、サーバー側にmaster.keyの情報を渡しておく必要があるため以下のコマンド実行
```
```
$ heroku config:set RAILS_MASTER_KEY=`cat config/master.key`
```
Heroku上でSelenium動かないため、以下コマンド実行する必要あり
```
$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-google-chrome
```
