### ISSUE TITLE
「GitHubでログイン」を押すと「ログインしてください」アラートが出てログインできない

### ISSUE THREAD

**Issue by pekorinko** [pekorinko/review_check#91]
プルリク #92
![image](https://user-images.githubusercontent.com/61894818/120909941-818fd780-c6b5-11eb-9d2f-fb1843fa324d.png)

**Comment by pekorinko** [comment]
## 原因として考えられること
- testブランチをHerokuにデプロイするためにGitHubの`OAuth application settings`にて新たに本番環境用の`review_check_production`を作った
- これにより`Client ID`や`Client secrets`が変更され、ローカルでログインできない事態を招いているのか？
## 結果：上記は原因ではない
- `EDITOR=vim bin/rails credentials:edit`を実行して現在設定されている`Client ID`や`Client secrets`を確認したところ、開発用の`Client ID`が`Client secrets`設定されていたため
## 参考：`EDITOR=vim bin/rails credentials:edit`
- `config/credentials.yml.enc`を開いて編集するためのコマンド
- 冒頭で``EDITOR=vim`とエディタを指定しないと開けないケースがある

**Comment by pekorinko** [comment]
## ローカルに残っていた`test`ブランチでログインを試みたところログイン出来た
### 対応方針
- ログイン関連のローカルとmainの差分を見ていく
![image](https://user-images.githubusercontent.com/61894818/120910519-958a0800-c6ba-11eb-96c5-b739f02d654e.png)

**Comment by pekorinko** [comment]
## routes.rbにtestとmainから切ったlogin_bug間に差分があった
```
【testブランチ routes.rb】
class AuthenticatedConstraint
  def matches?(request)
    request.session['user_id'].present?
  end
end

Rails
  .application
  .routes
  .draw do
    constraints AuthenticatedConstraint.new do
      root to: 'results#index', as: :user_root
    end

    root 'results#new'
    get '/auth/:provider/callback' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'
    resources :results, only: %i[new create index show]
  end
```
### ↓ログイン用のルーティングが無い
```
【login_bugブランチ routes.rb】
Rails
  .application
  .routes
  .draw do
    root 'results#new'
    get '/auth/:provider/callback' => 'sessions#create'
    delete '/logout' => 'sessions#destroy'
    resources :results, only: %i[new create index show]
  end

```

**Comment by pekorinko** [comment]
## ルーティングを直した結果以下エラーが出る
```
NoMethodError (undefined method `results' for #<User:0x00007fb9eef86010>):
  
app/controllers/results_controller.rb:7:in `index'
```
![image](https://user-images.githubusercontent.com/61894818/120912483-6aa7b000-c6ca-11eb-8b69-78ee77b468b4.png)

**Comment by pekorinko** [comment]
## routes.rbにログイン用のルーティングを書くと`NoMethodError (undefined method `results'`になる
```
【routes.rb ログイン用ルーティング】
class AuthenticatedConstraint
  def matches?(request)
    request.session['user_id'].present?
  end
end

Rails
  .application
  .routes
  .draw do
    constraints AuthenticatedConstraint.new do
      root to: 'results#index', as: :user_root
    end
```
```
NoMethodError (undefined method `results' for #<User:0x00007fb9eef86010>):
  
app/controllers/results_controller.rb:7:in `index'
```
![image](https://user-images.githubusercontent.com/61894818/120912483-6aa7b000-c6ca-11eb-8b69-78ee77b468b4.png)

**Comment by pekorinko** [comment]
## 現時点 6/6（日）14:20時点
- ログイン用のルーティングを書き足しても`NoMethodError (undefined method results`にはならなくなったが「GitHubでログイン」ボタンを押すと「ログインしてください」アラートが出るようになった
![image](https://user-images.githubusercontent.com/61894818/120913505-95960200-c6d2-11eb-90c3-fed48d1b32c4.png)

**Comment by pekorinko** [comment]
## mainブランチにはresultsテーブルとuserの関連付けを行っている20210429023145_add_references_to_results2.rbが存在しないことが原因か？
- mainから生やした`login_bug`ブランチにてresultsテーブルとuserの関連付けを行う`20210429023145_add_references_to_results2.rb`を新たに作った
### 結果
- ログインできない
```
【20210429023145_add_references_to_results2.rb】
class AddReferencesToResults2 < ActiveRecord::Migration[6.1]
  def change
    add_reference :results, :user, foreign_key: true
  end
end
```
```
database: review_check_development

 Status   Migration ID    Migration Name
--------------------------------------------------
   up     20210302124301  Create places
   up     20210302124316  Create reviews
   up     20210403053904  Add lrd to places
   up     20210412084426  Create results
   up     20210415081021  Add references to results
   up     20210419060241  Remove place name from results
   up     20210419060557  Remove address from results
   up     20210425015442  Create users
   up     20210429023145  Add references to results2　←追加したファイルもupの状態
   up     20210517225647  Add column to places
   up     20210523111332  Add url to places
```

**Comment by pekorinko** [comment]
## testブランチは通常通りログイン出来るため、testブランチから`login_bug_from_test`ブランチを切って対応することにした
- testブランチではcheck_credibility.rbファイル及び当ファイルのクラス名変更などは反映されていない
- 口コミボタンありの検索URLが入力された際に口コミボタンを押してモーダルを表示させて口コミURLを取得してスクレイピングを行う処理は反映されていない
-  **↑上記２つの処理を反映させた上で`login_bug_from_test`ブランチでログイン出来るのかを検証する**
-  **↑の検証が成功したらローカルのmainブランチに`login_bug_from_test`ブランチをマージしてmainブランチでもログイン出来るのか検証する**

**Comment by pekorinko** [comment]
## 結果
- selenium_tool.rbで口コミモーダルを自動で出現させる処理を書き加えた
- selenium_tool.rbで取得した口コミモーダルURLを place_data_scraper.rbのinitializeメソッドに渡す処理を書き加えた
- **その結果、口コミボタンありの検索URL入力して調査ボタンを押すと`口コミの取得に失敗しました`エラーが出る**
- そのため、results_controller.rbのcreateメソッドのbegin~rescue間に`binding.pry`を入れてどこでエラーが発生しているのかを確かめた
- すると`place_data_scraper = MyTools::PlaceDataScraper.new(@url)`を実行するとエラーが起きて`rescue`に飛んでしまうことがわかった
```
34: def create
    35:   @url = params[:url]
    36: 
    37:   url_filter = MyTools::UrlFilter.new(@url)
    38:   @url = url_filter.filter
    39: 
    40:   url_validator = MyTools::UrlValidator.new(@url)
    41: 
    42:   if url_validator.validate
    43:     begin
    44:       binding.pry
 => 45:       place_data_scraper = MyTools::PlaceDataScraper.new(@url)
    46:       place = place_data_scraper.save_place
    47:       place_id = place.id
    48:       place_data_scraper.save_review(place_id)
    49:       @place = place_data_scraper.save_place
    50:       user_id = session[:user_id]
    51:       check_credibility = MyTools::CheckCredibility.new(place_id)
    52:       @result = check_credibility.credibility(user_id)
```
```
34: def create
    35:   @url = params[:url]
    36: 
    37:   url_filter = MyTools::UrlFilter.new(@url)
    38:   @url = url_filter.filter
    39: 
    40:   url_validator = MyTools::UrlValidator.new(@url)
    41: 
    42:   if url_validator.validate
    43:     begin
    44:       binding.pry
    45:       place_data_scraper = MyTools::PlaceDataScraper.new(@url)
    46:       place = place_data_scraper.save_place
    47:       place_id = place.id
    48:       place_data_scraper.save_review(place_id)
    49:       @place = place_data_scraper.save_place
    50:       user_id = session[:user_id]
    51:       check_credibility = MyTools::CheckCredibility.new(place_id)
    52:       @result = check_credibility.credibility(user_id)
    53:       redirect_to result_path(@result)
 => 54:     rescue StandardError
    55:       redirect_to root_path, alert: '口コミの取得に失敗しました'
    56:     end
```

**Comment by pekorinko** [comment]
## selenium_tool.rbで以下修正を行った
### selenium_tool.rbの修正に至った経緯と仮説
- place_data_scraper.rbのinitializeメソッドでは`MyTools::SeleniumTool.new(url)`をしてselenium_tool.rbのインスタンスを作っているためselenium_tool.rbそのもの、及び当該ファイルのinitalizeメソッドがおかしいのでは無いかと仮説を立てた
- attr_reader :url`の書き忘れ解消
- `Selenium::WebDriver.for :chrome, options: options`を代入する`@driver`変数が`@d`となってる箇所があったため、全て`@driver`に統一した
- **`wait`を`@wait`に変更（initializeメソッドとは別に`replace_url_if_needed`でも`wait`を使用することからインスタンス変数にする必要がある）**
  - @waitとしてインスタンス変数に変更したことで 口コミボタンありの検索URL入力して調査ボタンを押すと自動でボタンを押して口コミモーダルのURLを取得してスクレイピング出来るようになった

**Comment by pekorinko** [comment]
## 解決
### ログイン出来なかった根本的原因→mainに以下内容が反映されていなかった　プルリク #92 
- ログイン用のルーティング追加 fa8871d
- ログイン者の調査履歴の情報を作成するクラス`lib/my_tools/search_history.rb`がmainブランチに存在していなかったため新規作成 6b01042
- `lib/my_tools/credibility_checker.rb`のResultテーブルを作成する際に`user_id: user_id,`の項目が抜けていたため解消 82c5865
- UserテーブルとResultテーブルの一対多の関連付け漏れ解消 d2b8612
- `app/controllers/sessions_controller.rb`における`skip_before_action :authenticate`の記載漏れ解消 82c5865
